
// ARALGIS.cpp : Defines the class behaviors for the application.
//

#include "stdafx.h"
#include "afxwinappex.h"
#include "afxdialogex.h"
#include "ARALGIS.h"
#include "MainFrm.h"

#include "ARALGISDoc.h"
#include "ARALGISView.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

// variable to control whether the program is started.
// if started, during exit the database  connections are closed
// eitherwise the connections are not tried to be closed
BOOL g_isProgramStarted;

// something like a counting semaphore for thread sync
int threadSyncCnt;

// used for calculating time using number of ticks generated by timer
int TimerNormalizer;

// event used for starting camera data reception
HANDLE g_CameraStartDataRecieveEvent;

// event used for stopping camera data reception
HANDLE g_CameraStopDataRecieveEvent;

// event used for changing camera sample rate
HANDLE g_CameraChangeSampleRateEvent;

// event used for pausing camera data reception
HANDLE g_CameraPauseDataRecieveEvent;

// event used for displaying camera configuration file selection dialog
HANDLE g_CameraConfigFileChangeEvent;

// event used for loading a recorded stream file 
HANDLE g_CameraSelectStreamFileEvent;

// event used for updating camera controls 
HANDLE g_CameraUpdateControlsEvent;

// event used for displaying BITMAP Window 
HANDLE g_DisplayBitmapEvent;

// event used for displaying OpenCV Window 
HANDLE g_DisplayOpenCVEvent;

// event used for setting timer frame rate 
HANDLE g_SetTimerFrameRateEvent;

// event used for killing timer 
HANDLE g_KillTimerEvent;

// event used for resetting timer 
HANDLE g_ResetTimerEvent;

// event used for resetting timer 
//HANDLE g_CameraDataReadyEvent;

// global variable to hold CV image from Camera
cv::Mat g_CVImage;

// Critical Section to protect isDatabaseHandlingInProgress
CRITICAL_SECTION g_SomeHandlingCS;

// event used for triggering PTS 
HANDLE g_PTSTriggerEvent;

// event used for triggering PTS 
HANDLE g_PTSLostEvent;

// event used for sending open barrier message to odroid 
HANDLE g_OdroidOpenBarrierEvent;

// event used for sending close barrier message to odroid  
HANDLE g_OdroidCloseBarrierEvent;

// event used for sending start heating message to odroid 
HANDLE g_OdroidStartHeatingEvent;

// event used for sending stop heating message to odroid 
HANDLE g_OdroidStopHeatingEvent;

// event used for sending start alarm message to odroid 
HANDLE g_OdroidStartAlarmEvent;

// event used for sending stop alarm message to odroid 
HANDLE g_OdroidStopAlarmEvent;

// PTS IP
char g_PtsIP[IP_ADDRESS_LEN + 1];

// PLAKA NUMBER
char g_PlakaNoChars[PLAKA_CHAR_LENGTH+1];

// CAR FRONTAL/PLAKA IMAGE 
BYTE* g_CarPlakaImage;
int m_CarPlakaImageLenght;




// CARALGISApp

BEGIN_MESSAGE_MAP(CARALGISApp, CWinApp)
	ON_COMMAND(ID_APP_ABOUT, &CARALGISApp::OnAppAbout)
	// Standard file based document commands
	ON_COMMAND(ID_FILE_NEW, &CWinApp::OnFileNew)
	ON_COMMAND(ID_FILE_OPEN, &CWinApp::OnFileOpen)
	// Standard print setup command
	ON_COMMAND(ID_FILE_PRINT_SETUP, &CWinApp::OnFilePrintSetup)
END_MESSAGE_MAP()


// CARALGISApp construction

CARALGISApp::CARALGISApp()
{
	// support Restart Manager
	m_dwRestartManagerSupportFlags = AFX_RESTART_MANAGER_SUPPORT_ALL_ASPECTS;
#ifdef _MANAGED
	// If the application is built using Common Language Runtime support (/clr):
	//     1) This additional setting is needed for Restart Manager support to work properly.
	//     2) In your project, you must add a reference to System.Windows.Forms in order to build.
	System::Windows::Forms::Application::SetUnhandledExceptionMode(System::Windows::Forms::UnhandledExceptionMode::ThrowException);
#endif

	// TODO: replace application ID string below with unique ID string; recommended
	// format for string is CompanyName.ProductName.SubProduct.VersionInformation
	SetAppID(_T("ARALGIS.AppID.NoVersion"));

	// TODO: add construction code here,
	// Place all significant initialization in InitInstance
}

// The one and only CARALGISApp object

CARALGISApp theApp;


BOOL CARALGISApp::InitInstance()
{
	/// boraN
	_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);

	// InitCommonControlsEx() is required on Windows XP if an application
	// manifest specifies use of ComCtl32.dll version 6 or later to enable
	// visual styles.  Otherwise, any window creation will fail.
	INITCOMMONCONTROLSEX InitCtrls;
	InitCtrls.dwSize = sizeof(InitCtrls);
	// Set this to include all the common control classes you want to use
	// in your application.
	InitCtrls.dwICC = ICC_WIN95_CLASSES;
	InitCommonControlsEx(&InitCtrls);

	CWinApp::InitInstance();


	// Initialize OLE libraries
	if (!AfxOleInit())
	{
		AfxMessageBox(IDP_OLE_INIT_FAILED);
		return FALSE;
	}

	AfxEnableControlContainer();

	EnableTaskbarInteraction(FALSE);

	// AfxInitRichEdit2() is required to use RichEdit control	
	// AfxInitRichEdit2();

	// Standard initialization
	// If you are not using these features and wish to reduce the size
	// of your final executable, you should remove from the following
	// the specific initialization routines you do not need
	// Change the registry key under which our settings are stored
	// TODO: You should modify this string to be something appropriate
	// such as the name of your company or organization
	SetRegistryKey(_T("FuzyonSoft ARALGIS"));
	LoadStdProfileSettings(4);  // Load standard INI file options (including MRU)


	// Register the application's document templates.  Document templates
	//  serve as the connection between documents, frame windows and views
	CSingleDocTemplate* pDocTemplate;
	pDocTemplate = new CSingleDocTemplate(
		IDR_MAINFRAME,
		RUNTIME_CLASS(CARALGISDoc),
		RUNTIME_CLASS(CMainFrame),       // main SDI frame window
		RUNTIME_CLASS(CARALGISView));
	if (!pDocTemplate)
		return FALSE;
	AddDocTemplate(pDocTemplate);


	// Parse command line for standard shell commands, DDE, file open
	CCommandLineInfo cmdInfo;
	ParseCommandLine(cmdInfo);

	// Dispatch commands specified on the command line.  Will return FALSE if
	// app was launched with /RegServer, /Register, /Unregserver or /Unregister.
	if (!ProcessShellCommand(cmdInfo))
		return FALSE;

	// The one and only window has been initialized, so show and update it
	m_pMainWnd->ShowWindow(SW_SHOW);
	m_pMainWnd->UpdateWindow();

	CFrameWnd *pFrame = (CFrameWnd *)(AfxGetApp()->m_pMainWnd);
	CView * pView = pFrame->GetActiveView();

	// added by bora  --->not a debug debugBN
	//((CMainFrame*)m_pMainWnd)->Activate();
	((CMainFrame*)m_pMainWnd)->Activate();


	return TRUE;
}

int CARALGISApp::ExitInstance()
{
	//TODO: handle additional resources you may have added
	AfxOleTerm(FALSE);

	_CrtDumpMemoryLeaks();


	return CWinApp::ExitInstance();
}

// CARALGISApp message handlers


// CAboutDlg dialog used for App About

class CAboutDlg : public CDialogEx
{
public:
	CAboutDlg();

	// Dialog Data
	enum { IDD = IDD_ABOUTBOX };

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

	// Implementation
protected:
	DECLARE_MESSAGE_MAP()
};

CAboutDlg::CAboutDlg() : CDialogEx(CAboutDlg::IDD)
{
}

void CAboutDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialogEx::DoDataExchange(pDX);
}

BEGIN_MESSAGE_MAP(CAboutDlg, CDialogEx)
END_MESSAGE_MAP()

// App command to run the dialog
void CARALGISApp::OnAppAbout()
{
	CAboutDlg aboutDlg;
	aboutDlg.DoModal();
}

// CARALGISApp message handlers
